### ISSUE TITLE
Is it possible to upload an experiment to a server?

### ISSUE THREAD

**Issue by orenpapers** [expfactory/expfactory.github.io#14]
In order to send it to participant, for them to do it online?

**Comment by vsoch** [comment]
When you run an experiment container, it deploys / exposes the experiment to the localhost, so yes, if you run a container on a remote server (e.g., a cloud server or other that you host) the experiment will be available at the server address. Does this answer your question?

**Comment by orenpapers** [comment]
@vsoch Sure thanks!
Is there a guide/tutorial explaining how to set up the expfactory and be able to start collecting data?

**Comment by vsoch** [comment]
Yep https://expfactory.github.io/generate#quick-start
